### ISSUE TITLE
put the text to the right side of the question mark

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_global_zoom#1]
用 Savor 看起来有点怪：

![image](https://github.com/user-attachments/assets/88df42fa-e274-4510-99d3-e228b299c9f3)

**Comment by zxkmm** [comment]
谢谢,等我把css删掉看看。不过现在思源集市没有同步最新版，不知道为啥

**Comment by TCOTC** [comment]
我这里已经是 0.0.2 了

**Comment by zxkmm** [comment]
我不知道套用字符数那个div的样式会不会有问题。等我先尝试一下

**Comment by zxkmm** [comment]
看起来套用那个样式没啥问题，下版本更新
![image](https://github.com/user-attachments/assets/e8344cfd-4493-4409-8571-d064836fa1b2)

**Comment by zxkmm** [comment]
话说前面该不该加个“缩放值”的文案？还是加个icon更好？

**Comment by TCOTC** [comment]
我觉得不用，简洁最好

**Comment by zxkmm** [comment]
好的 谢谢

**Comment by zxkmm** [comment]
53a40c856a8251938a3c38f13dd23820fddd0514

**Comment by zxkmm** [comment]
不能套用字符统计的css,因为会让悬浮标签失效
添加了一个css class`zoom_content_for_theme`供第三方主题使用适配

**Comment by TCOTC** [comment]
我感觉那个悬浮提示没什么用，只是将百分比重复显示了一遍

**Comment by zxkmm** [comment]
那个悬浮提示是另一个计算的结果，例如显示为倍数的时候，悬浮里面是百分比，显示为百分比时候，里面是倍数
然后字体大小也是基于px计算百分比，还是有点用的

**Comment by TCOTC** [comment]
原来如此

**Comment by TCOTC** [comment]
所以是改成直接应用样式咯？

```
display: flex;
flex-shrink: 0;
font-size: 12px;
color: var(--b3-theme-on-surface);
```

**Comment by zxkmm** [comment]
我之后PR到第三方主题。或者或许有更好的方案但我不知道，因为我不懂css

**Comment by zxkmm** [comment]
> 所以是改成直接应用样式咯？

现阶段我只能做到把这个css加给三方主题，然后三方主题用那个css来调到顺眼。或许有更合理的方案

**Comment by zxkmm** [comment]
```zoomInfoElement.classList.add("ariaLabel", "zoom_content", "zoom_content_for_theme"); //3rd party theme use zoom_content_for_theme to style me.```

**Comment by TCOTC** [comment]
用 status__counter 有什么问题吗？

**Comment by zxkmm** [comment]
> 用 status__counter 有什么问题吗？

会导致悬浮标签失效

**Comment by TCOTC** [comment]
为啥我在 DOM 里加的时候没问题

![image](https://github.com/user-attachments/assets/b8747a12-73e0-4804-9e04-ac6137864ba6)

![image](https://github.com/user-attachments/assets/1ed1efdc-4a60-4740-919b-1f865112abe5)

**Comment by zxkmm** [comment]
这样加了在savor主题也会显示错乱，因为ariaLabel还在

**Comment by zxkmm** [comment]
对了 这个浮点我忘记处理了😂Linux下面是整数

**Comment by TCOTC** [comment]
> 这样加了在savor主题也会显示错乱，因为ariaLabel还在

我没明白

![image](https://github.com/user-attachments/assets/06f54615-b718-4cf2-b3e7-c99f9672ff23)

**Comment by zxkmm** [comment]
🫣怪，为啥我这里不行，等我再康康

**Comment by TCOTC** [comment]
另外 "AKA" 多余了

**Comment by zxkmm** [comment]
> 另外 "AKA" 多余了

主要是因为因为设置里也是这样写的。但要改掉也行。

**Comment by zxkmm** [comment]
https://github.com/zxkmm/siyuan_global_zoom/releases/tag/v0.0.5

**Comment by TCOTC** [comment]
在默认主题下能不能移到问号的左边显示？中间凸起一个按钮感觉有点怪

![image](https://github.com/user-attachments/assets/0eaf6e91-b01f-41c5-93e7-456b818fb1d0)

**Comment by zxkmm** [comment]
这个我也想，但不会写😂

**Comment by zxkmm** [comment]
之前没有想到插件可以改其他div的css.
现在解决了.
ref: https://github.com/zxkmm/siyuan_main_window_modification
